# 网站标题
title: 中央大學國際處電子報
# 网站标题后缀
suffix: 國際處電子報
# 作者名称
author: 中央大學國際處
# 网站关键字
keyword: 
#false是否开启文章背景图显示(随机图片)
is_article_img: true  
# 网站描述
web_description: 描述
# 首页文章布局 默认 'card' 可选择 'block-card'
home_layout: card
# 导航名称
menus_title:
  home: 首頁
  archive: 過往電子報
  categories: CATEGORIES
  tags: TAGS
  links: LINKS
  about: ABOUT
  subscribe: 訂閱入口
  oia: 國際處首頁
# 导航 （不建议修改）
menus:
  home: /
  archive: /archives
  subscribe: https://epaper.ncu.edu.tw/subscribe?pid=40
  oia: https://www.oia.ncu.edu.tw/
# logo
logo: /image/logo.webp
# 网页标签上那个小图标 一定要用本地存储
icon: /image/favicon.ico
# 每个页面的展示的图标和一句话
headers:
    home: {
      message: "國際處電子報<br>Office of International Affairs E-paper",
      icon: "/image/logo.webp"
    }
    archives: {
      # 这里会替换掉两个变量{ year 年，number 总数 } 当然也可以不写这两个变量
      message: "過往電子報<br>Archives",
      icon: "https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imgicon-remixicon.svg"
    }
    tags: {
      message: "这里是一些展示的标签",
      icon: "https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imgtags.svg"
    }
    links: {
      message: "我和我的小伙伴们",
      icon: "https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imga20r7-cftji.svg"
    }
    categories: {
      message: "文章分类",
      icon: "https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imgblogmyCategory.svg"
    }

# 网页访问统计
web_analytics:  
  enable: false #需要改为true
  baidu: 4b5fe1472f22fadsfs  # （替换）百度统计的 Key，参见 https://tongji.baidu.com/sc-web/10000033910/home/site/getjs?siteId=13751376 代码获取中 hm.js? 后边的字符串
# 评论 
gitalk:
  clientID: 02b3c # （需要替换）GitHub Application Client ID.
  clientSecret: adfc7b4 #（需要替换）GitHub Application Client Secret.
  repo: gimment #（需要替换）GitHub repository.
  owner: duneng #（需要替换）GitHub repository 所有者，可以是个人或者组织。
  admin: ['duneng'] #（需要替换）GitHub repository 的所有者和合作者 (对这个 repository 有写权限的用户)。

# 底部显示的图标（github 或者其他）
bottomIcon: 
  #可以多个
  - {
    #描述名称
    name: 'OIA',
    #图标    
    iconLink: '/images/ncu.png',
    #跳转链接    
    toUrl: 'https://www.oia.ncu.edu.tw/'
  }
# 友情链接
linksList:
  - {
    title: 'OIA',
    intro: '',
    link: 'https://',
    image: 'https://cdn.jsdelivr.net/gh/duogongneng/MyBlogImg/imgIMG_7327.jpeg'
  }

#默认的cover (默认缩略图) 在没有填写（这里可以替换（可以是api也可以是固定的图））
# https://api.ixiaowai.cn/gqapi/gqapi.php
# https://tuapi.eees.cc/api.php?type=302&category=fengjing
default_cover: https://api.ixiaowai.cn/gqapi/gqapi.php
